import { Inter } from "next/font/google";
import "./globals.css";

const geistInter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR" className={`${geistInter.variable} h-full antialiased`}>
      <body className="w-full min-h-full flex flex-col">
        <a
          href="#main"
          className="sr-only focus:not-sr-only fixed z-50 top-4 left-4 bg-black text-white px-3 py-2 rounded-md"
        >
          Pular para o conteúdo
        </a>
        <main id="main" className="w-full">
          {children}
        </main>
      </body>
    </html>
  );
}
